import { c as create_ssr_component } from "../../chunks/ssr.js";
import { e as escape } from "../../chunks/escape.js";
const css = {
  code: "body{margin:0;padding:0}",
  map: `{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script>\\n  import { onMount } from 'svelte';\\n  \\n  let status = 'Loading...';\\n  \\n  onMount(() => {\\n    status = 'JustFlash Deployment Dashboard - Operational';\\n  });\\n<\/script>\\n\\n<div class=\\"min-h-screen bg-gradient-to-br from-gray-900 to-gray-800 text-white p-8\\">\\n  <div class=\\"max-w-7xl mx-auto\\">\\n    <h1 class=\\"text-4xl font-bold mb-8 bg-gradient-to-r from-blue-400 to-purple-600 bg-clip-text text-transparent\\">\\n      JustFlash Deployment Control Center\\n    </h1>\\n    \\n    <div class=\\"bg-gray-800/50 backdrop-blur-sm rounded-xl p-6 border border-gray-700/50\\">\\n      <h2 class=\\"text-2xl font-semibold mb-4\\">System Status</h2>\\n      <p class=\\"text-gray-300\\">{status}</p>\\n      \\n      <div class=\\"mt-8 grid grid-cols-1 md:grid-cols-3 gap-4\\">\\n        <div class=\\"bg-gray-700/50 rounded-lg p-4\\">\\n          <h3 class=\\"text-lg font-medium mb-2\\">🚀 Deployment</h3>\\n          <p class=\\"text-green-400\\">Ready</p>\\n        </div>\\n        \\n        <div class=\\"bg-gray-700/50 rounded-lg p-4\\">\\n          <h3 class=\\"text-lg font-medium mb-2\\">📊 Monitoring</h3>\\n          <p class=\\"text-yellow-400\\">Configuring</p>\\n        </div>\\n        \\n        <div class=\\"bg-gray-700/50 rounded-lg p-4\\">\\n          <h3 class=\\"text-lg font-medium mb-2\\">🔐 Security</h3>\\n          <p class=\\"text-green-400\\">Active</p>\\n        </div>\\n      </div>\\n    </div>\\n    \\n    <div class=\\"mt-8 text-center text-gray-500\\">\\n      <p>Native Flash Loan Protocol for TRX</p>\\n    </div>\\n  </div>\\n</div>\\n\\n<style>\\n  :global(body) {\\n    margin: 0;\\n    padding: 0;\\n  }\\n</style>\\n"],"names":[],"mappings":"AA6CU,IAAM,CACZ,MAAM,CAAE,CAAC,CACT,OAAO,CAAE,CACX"}`
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let status = "Loading...";
  $$result.css.add(css);
  return `<div class="min-h-screen bg-gradient-to-br from-gray-900 to-gray-800 text-white p-8"><div class="max-w-7xl mx-auto"><h1 class="text-4xl font-bold mb-8 bg-gradient-to-r from-blue-400 to-purple-600 bg-clip-text text-transparent" data-svelte-h="svelte-1z1bdz">JustFlash Deployment Control Center</h1> <div class="bg-gray-800/50 backdrop-blur-sm rounded-xl p-6 border border-gray-700/50"><h2 class="text-2xl font-semibold mb-4" data-svelte-h="svelte-1ndlnmr">System Status</h2> <p class="text-gray-300">${escape(status)}</p> <div class="mt-8 grid grid-cols-1 md:grid-cols-3 gap-4" data-svelte-h="svelte-193afa9"><div class="bg-gray-700/50 rounded-lg p-4"><h3 class="text-lg font-medium mb-2">🚀 Deployment</h3> <p class="text-green-400">Ready</p></div> <div class="bg-gray-700/50 rounded-lg p-4"><h3 class="text-lg font-medium mb-2">📊 Monitoring</h3> <p class="text-yellow-400">Configuring</p></div> <div class="bg-gray-700/50 rounded-lg p-4"><h3 class="text-lg font-medium mb-2">🔐 Security</h3> <p class="text-green-400">Active</p></div></div></div> <div class="mt-8 text-center text-gray-500" data-svelte-h="svelte-1nzvps2"><p>Native Flash Loan Protocol for TRX</p></div></div> </div>`;
});
export {
  Page as default
};
